### ISSUE TITLE
[Feature Request] Separators

### ISSUE THREAD

**Issue by imerkle** [javierbyte/react-number-easing#10]
Add separators 120,000 .

**Comment by che-wf** [comment]
@dsslimshaddy This can be addressed using the `useLocaleString` prop. [Look here](https://github.com/javierbyte/react-number-easing#props).  I also have a fork with a little more detailed information [here](https://github.com/jbcoder/react-number-easing#props).

**Comment by javierbyte** [comment]
@che-wf amazing work there! thanks!

@imerkle the newest version on this repo also supports custom functions that could solve your issue.
