### ISSUE TITLE
Continued support

### ISSUE THREAD

**Issue by cryptism** [javierbyte/react-number-easing#12]
Despite this widget being broken in the latest versions of React, it looks like there is still a small but present need for this tool to be maintained among some. Any chance you might think about adding some maintainers for this, if you're too busy? Happy to chip in myself.

**Comment by s-tkachenko** [comment]
@cryptism try this fork - https://github.com/jbcoder/react-number-easing
It perfectly works with the last version of React

**Comment by javierbyte** [comment]
Hello, sorry for the late reply. @cryptism and @s-tkachenko not sure if you are still using this package years later but I just updated it and would be willing to give some more time to bring maintainers if there is people still using the tool, thanks!
