### ISSUE TITLE
Going to different tab in Chrome causes numbers to be way off

### ISSUE THREAD

**Issue by neurosnap** [javierbyte/react-number-easing#5]
![ease](https://cloud.githubusercontent.com/assets/1940365/9641767/5e1aa104-5186-11e5-96a1-ead9a342d2b0.jpg)

For whatever reason, in Google Chrome, when you switch to a different tab and let the numbers update, and then go back to the original tab, it causes the numbers to be way off.  This seems related to #3

**Comment by criso** [comment]
Running into this as well

**Comment by neurosnap** [comment]
Curious about updates on this issue?  A library like https://www.npmjs.com/package/visibility might help in getting around this issue.
