### ISSUE TITLE
Unknown prop `ease` on <span> tag

### ISSUE THREAD

**Issue by mindtricksdev** [javierbyte/react-number-easing#8]
It seems that React is causing an unknown prop error in the console because of the prop ease being passed to span DOM element.

The fix is explained here https://facebook.github.io/react/warnings/unknown-prop.html and it is pretty simple. You need to avoid passing `ease` to `span `as a prop.

Thanks,

**Comment by mindtricksdev** [comment]
Actually, there's a pull request already. 
 #7

**Comment by javierbyte** [comment]
Hello, sorry for the late reply, the newest version should solve this issue.
