### ISSUE TITLE
Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by mindtricksdev** [javierbyte/react-number-easing#9]
Hello,

PropTypes has been moved to a separate package. Accessing it via React.PropTypes triggers a warning in DevConsole.

![image](https://user-images.githubusercontent.com/5068284/29495419-7d776ef2-85c7-11e7-800f-87650ef772af.png)

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
There's a codemode to automate the transition.

Thanks!

**Comment by che-wf** [comment]
This also should be taken care of in [#11](https://github.com/javierbyte/react-number-easing/issues/11) via @kunukn.

**Comment by javierbyte** [comment]
@che-wf thanks!

I think anyone looking for a solution for this could probably use https://github.com/che-wf/react-number-easing instead for now. I'll add proptypes to the hooks version soon.
